apiVersion: skaffold/v2alpha3
kind: Config
deploy: # Watch the Deployment file
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build: # Watch the Docker file
  local:
    push: false
  artifacts:
    - image: wahaha007/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts' # include multi level dir
            dest: .

    - image: wahaha007/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .

    - image: wahaha007/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts' # include multi level dir
            dest: .

    - image: wahaha007/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts' # include multi level dir
            dest: .

    - image: wahaha007/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .

    - image: wahaha007/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
